#!/usr/bin/env python3
# toolchain/genfont.py
# Regenerates kernel/font8x16.h from an 8x16 Linux console PSF font.
# Needs the `kbd` package installed (provides /usr/share/consolefonts/*.psf.gz).
import gzip
import glob
import os
import struct
import sys

PREFERRED_FONTS = [
    "Lat15-Fixed16", "Lat2-Fixed16", "Lat7-Fixed16", "Uni2-Fixed16",
    "Lat15-VGA16", "Lat15-TerminusBoldVGA16", "Lat15-Terminus16",
]
FONT_DIR = "/usr/share/consolefonts"


def read_gz(path):
    with gzip.open(path, "rb") as fh:
        return fh.read()


def parse_psf(data):
    if data[0:2] == b"\x36\x04":
        return _parse_psf1(data)
    if data[0:4] == b"\x72\xb5\x4a\x86":
        return _parse_psf2(data)
    raise SystemExit("unrecognized PSF magic")


def _parse_psf1(data):
    mode, charsize = data[2], data[3]
    glyph_count = 512 if (mode & 0x01) else 256
    glyphs = data[4:4 + glyph_count * charsize]

    unicode_map = None
    if mode & 0x02:
        unicode_map = {}
        tail = data[4 + glyph_count * charsize:]
        pairs = len(tail) // 2
        glyph_idx = 0
        for codepoint in struct.unpack("<%dH" % pairs, tail[:pairs * 2]):
            if codepoint == 0xFFFF:
                glyph_idx += 1
            elif codepoint != 0xFFFE:
                unicode_map.setdefault(codepoint, glyph_idx)
    return 8, charsize, charsize, glyph_count, glyphs, unicode_map


def _parse_psf2(data):
    _, header_len, flags, glyph_count, charsize, height, width = \
        struct.unpack("<IIIIIII", data[4:32])
    glyphs = data[header_len:header_len + glyph_count * charsize]

    unicode_map = None
    if flags & 0x01:
        unicode_map = {}
        tail = data[header_len + glyph_count * charsize:]
        glyph_idx = 0
        for token in tail.split(b"\xff"):
            for ch in token.decode("utf-8", "ignore"):
                unicode_map.setdefault(ord(ch), glyph_idx)
            glyph_idx += 1
    return width, height, charsize, glyph_count, glyphs, unicode_map


def pick_font():
    candidates = [os.path.join(FONT_DIR, name + ".psf.gz") for name in PREFERRED_FONTS]
    candidates += sorted(glob.glob(os.path.join(FONT_DIR, "*.psf.gz")))

    for path in candidates:
        if not os.path.exists(path):
            continue
        try:
            parsed = parse_psf(read_gz(path))
        except Exception:
            continue
        if parsed[0] == 8 and parsed[1] == 16:
            return os.path.basename(path), parsed

    raise SystemExit("no 8x16 font found - is the 'kbd' package installed?")


def glyph_bytes(codepoint, charsize, glyph_count, glyphs, unicode_map):
    idx = unicode_map.get(codepoint) if unicode_map is not None else codepoint
    if idx is None or idx >= glyph_count:
        return bytes(16)
    row = glyphs[idx * charsize: idx * charsize + 16]
    return row if row else bytes(16)


def main():
    font_name, (width, height, charsize, glyph_count, glyphs, unicode_map) = pick_font()
    sys.stderr.write(f"using font: {font_name} ({width}x{height}, {glyph_count} glyphs)\n")

    dest = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "kernel", "font8x16.h"))
    with open(dest, "w") as out:
        out.write("/* kernel/font8x16.h - generated by toolchain/genfont.py.\n")
        out.write(f" * 8x16 bitmap font (ASCII 0..127) from console font: {font_name}.\n")
        out.write(" * MSB = leftmost pixel. */\n")
        out.write("#ifndef PEFIA_FONT8X16_H\n#define PEFIA_FONT8X16_H\n\n")
        out.write("#define FONT_WIDTH  8\n#define FONT_HEIGHT 16\n\n")
        out.write("static const unsigned char font8x16[128][16] = {\n")
        for codepoint in range(128):
            row = glyph_bytes(codepoint, charsize, glyph_count, glyphs, unicode_map)
            values = ", ".join(f"0x{b:02X}" for b in row)
            out.write(f"    {{ {values} }}, /* 0x{codepoint:02X} */\n")
        out.write("};\n\n#endif /* PEFIA_FONT8X16_H */\n")

    sys.stderr.write(f"wrote {dest}\n")


if __name__ == "__main__":
    main()
