# toolchain/genfont.ps1
# Regenerates kernel/font8x16.h: an antialiased 8x16 grayscale-coverage font,
# rasterized from Consolas via GDI+ (AntiAliasGridFit). Windows-only, since
# that's where Consolas and GDI+ live; the output header is what's committed.
Add-Type -AssemblyName System.Drawing

$W = 8; $H = 16
$font = New-Object System.Drawing.Font("Consolas", 13.5, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
$sf = [System.Drawing.StringFormat]::GenericTypographic.Clone()
$sf.FormatFlags = $sf.FormatFlags -bor [System.Drawing.StringFormatFlags]::NoClip

$bmp = New-Object System.Drawing.Bitmap($W, $H)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* kernel/font8x16.h - GENERATED by toolchain/genfont.ps1 (GDI+ grayscale AA")
[void]$sb.AppendLine(" * render of Consolas 13.5px). 8x16 cell, ASCII 0..127. Each byte is glyph")
[void]$sb.AppendLine(" * coverage 0..255: 0 = background, 255 = full ink, else blend. */")
[void]$sb.AppendLine("#ifndef PEFIA_FONT8X16_H")
[void]$sb.AppendLine("#define PEFIA_FONT8X16_H")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#define FONT_WIDTH  8")
[void]$sb.AppendLine("#define FONT_HEIGHT 16")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("static const unsigned char font8x16aa[128][128] = {")

$nonEmpty = 0
for ($c = 0; $c -lt 128; $c++) {
    $vals = New-Object 'System.Collections.Generic.List[string]'
    if ($c -ge 33 -and $c -le 126) {
        $g.Clear([System.Drawing.Color]::Black)
        $g.DrawString([string][char]$c, $font, [System.Drawing.Brushes]::White, 0.2, 0.0, $sf)
        $g.Flush()
        $any = $false
        for ($y = 0; $y -lt $H; $y++) {
            for ($x = 0; $x -lt $W; $x++) {
                $v = $bmp.GetPixel($x, $y).R
                if ($v -gt 0) { $any = $true }
                $vals.Add("0x{0:X2}" -f $v)
            }
        }
        if ($any) { $nonEmpty++ }
    } else {
        for ($i = 0; $i -lt 128; $i++) { $vals.Add("0x00") }
    }
    [void]$sb.AppendLine(("    {{ /* 0x{0:X2}{1} */" -f $c, $(if ($c -ge 33 -and $c -le 126) { " '" + [char]$c + "'" } else { "" })))
    for ($row = 0; $row -lt $H; $row += 4) {
        $chunk = $vals.GetRange($row * $W, 4 * $W) -join ","
        [void]$sb.AppendLine("    $chunk,")
    }
    [void]$sb.AppendLine("    },")
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#endif /* PEFIA_FONT8X16_H */")

$g.Dispose(); $bmp.Dispose()
$dest = Join-Path $PSScriptRoot "..\kernel\font8x16.h"
[System.IO.File]::WriteAllText($dest, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Output "glyphs with ink: $nonEmpty / 94 expected"
