#!/usr/bin/env python3
# toolchain/genfont.py
# Generate ../kernel/font8x16.h from an 8x16 Linux console PSF font.
# Requires the `kbd` package (provides /usr/share/consolefonts/*.psf.gz).
import gzip, glob, struct, sys, os

CANDIDATES = [
    "Lat15-Fixed16", "Lat2-Fixed16", "Lat7-Fixed16", "Uni2-Fixed16",
    "Lat15-VGA16", "Lat15-TerminusBoldVGA16", "Lat15-Terminus16",
]
DIR = "/usr/share/consolefonts"

def load(path):
    with gzip.open(path, "rb") as f:
        return f.read()

def parse_psf(data):
    if data[0:2] == b"\x36\x04":  # PSF1
        mode = data[2]; charsize = data[3]
        count = 512 if (mode & 0x01) else 256
        glyphs = data[4:4 + count * charsize]
        uni = None
        if mode & 0x02:  # unicode table: stream of LE uint16, 0xFFFF ends glyph
            uni = {}
            rest = data[4 + count * charsize:]
            n = len(rest) // 2
            idx = 0
            for v in struct.unpack("<%dH" % n, rest[:n * 2]):
                if v == 0xFFFF: idx += 1
                elif v != 0xFFFE: uni.setdefault(v, idx)
        return 8, charsize, charsize, count, glyphs, uni
    if data[0:4] == b"\x72\xb5\x4a\x86":  # PSF2
        (_, hdr, flags, count, charsize, height, width) = struct.unpack("<IIIIIII", data[4:32])
        glyphs = data[hdr:hdr + count * charsize]
        uni = None
        if flags & 0x01:
            uni = {}
            rest = data[hdr + count * charsize:]
            idx = 0
            for token in rest.split(b"\xff"):
                for ch in token.decode("utf-8", "ignore"):
                    uni.setdefault(ord(ch), idx)
                idx += 1
        return width, height, charsize, count, glyphs, uni
    raise SystemExit("unknown PSF magic")

def pick():
    paths = [os.path.join(DIR, n + ".psf.gz") for n in CANDIDATES]
    paths += sorted(glob.glob(os.path.join(DIR, "*.psf.gz")))
    for p in paths:
        if not os.path.exists(p): continue
        try:
            w, h, cs, cnt, g, uni = parse_psf(load(p))
        except Exception:
            continue
        if w == 8 and h == 16:
            return os.path.basename(p), (w, h, cs, cnt, g, uni)
    raise SystemExit("no 8x16 font found (is the 'kbd' package installed?)")

name, (w, h, cs, cnt, glyphs, uni) = pick()
sys.stderr.write(f"using font: {name} ({w}x{h}, {cnt} glyphs)\n")

def glyph_for(cp):
    idx = uni.get(cp) if uni is not None else cp
    if idx is None or idx >= cnt:
        return bytes(16)
    return glyphs[idx * cs: idx * cs + 16] or bytes(16)

dest = os.path.join(os.path.dirname(__file__), "..", "kernel", "font8x16.h")
with open(os.path.abspath(dest), "w") as f:
    f.write("/* kernel/font8x16.h - GENERATED by toolchain/genfont.py.\n")
    f.write(f" * 8x16 bitmap font (ASCII 0..127) from console font: {name}.\n")
    f.write(" * MSB = leftmost pixel. */\n")
    f.write("#ifndef PEFIA_FONT8X16_H\n#define PEFIA_FONT8X16_H\n\n")
    f.write("#define FONT_WIDTH  8\n#define FONT_HEIGHT 16\n\n")
    f.write("static const unsigned char font8x16[128][16] = {\n")
    for cp in range(128):
        vals = ", ".join(f"0x{b:02X}" for b in glyph_for(cp))
        f.write(f"    {{ {vals} }}, /* 0x{cp:02X} */\n")
    f.write("};\n\n#endif /* PEFIA_FONT8X16_H */\n")
sys.stderr.write(f"wrote {os.path.abspath(dest)}\n")
